package com.dergoogler.mmrl.ui.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val MMRLBaseLightScheme =
    lightColorScheme(
        primary = Color(0xFF555992),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE0E0FF),
        onPrimaryContainer = Color(0xFF11144B),
        inversePrimary = Color(0xFFBEC2FF),
        secondary = Color(0xFF5C5D72),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE1E0F9),
        onSecondaryContainer = Color(0xFF191A2C),
        tertiary = Color(0xFF78536B),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFD8EE),
        onTertiaryContainer = Color(0xFF2E1126),
        background = Color(0xFFFBF8FF),
        onBackground = Color(0xFF1B1B21),
        surface = Color(0xFFFBF8FF),
        onSurface = Color(0xFF1B1B21),
        surfaceVariant = Color(0xFFE4E1EC),
        onSurfaceVariant = Color(0xFF46464F),
        surfaceTint = Color(0xFF555992),
        inverseSurface = Color(0xFF131318),
        inverseOnSurface = Color(0xFFE4E1E9),
        error = Color(0xFFB3261E),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFF9DEDC),
        onErrorContainer = Color(0xFF410E0B),
        outline = Color(0xFF777680),
        outlineVariant = Color(0xFFC7C5D0),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFFBF8FF),
        surfaceDim = Color(0xFFDBD9E0),
        surfaceContainer = Color(0xFFF0ECF4),
        surfaceContainerHigh = Color(0xFFEAE7EF),
        surfaceContainerHighest = Color(0xFFE4E1E9),
        surfaceContainerLow = Color(0xFFF5F2FA),
        surfaceContainerLowest = Color(0xFFFFFFFF),
    )

val MMRLBaseDarkScheme =
    darkColorScheme(
        primary = Color(0xFF8AADFF),
        onPrimary = Color(0xFF071226),
        primaryContainer = Color(0xFF1A2B4B),
        onPrimaryContainer = Color(0xFFD8E4FF),
        inversePrimary = Color(0xFF315FAD),
        secondary = Color(0xFFB9C3D3),
        onSecondary = Color(0xFF20262F),
        secondaryContainer = Color(0xFF242B34),
        onSecondaryContainer = Color(0xFFDCE3ED),
        tertiary = Color(0xFF86CFD8),
        onTertiary = Color(0xFF092126),
        tertiaryContainer = Color(0xFF18363B),
        onTertiaryContainer = Color(0xFFC5F1F5),
        background = Color(0xFF090B0E),
        onBackground = Color(0xFFF1F3F6),
        surface = Color(0xFF090B0E),
        onSurface = Color(0xFFF1F3F6),
        surfaceVariant = Color(0xFF20252C),
        onSurfaceVariant = Color(0xFFAAB2BD),
        surfaceTint = Color(0xFF8AADFF),
        inverseSurface = Color(0xFFE8EBF0),
        inverseOnSurface = Color(0xFF171A1F),
        error = Color(0xFFFF8E92),
        onError = Color(0xFF390006),
        errorContainer = Color(0xFF5B171C),
        onErrorContainer = Color(0xFFFFDADB),
        outline = Color(0xFF3A414B),
        outlineVariant = Color(0xFF252B33),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF242930),
        surfaceDim = Color(0xFF090B0E),
        surfaceContainer = Color(0xFF12151A),
        surfaceContainerHigh = Color(0xFF171B20),
        surfaceContainerHighest = Color(0xFF1D2229),
        surfaceContainerLow = Color(0xFF0F1216),
        surfaceContainerLowest = Color(0xFF07090C),
    )
