package com.dergoogler.mmrl.debug

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import java.io.File
import java.util.Locale
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/** Creates and shares a sanitized Debug Workbench support bundle. */
class DebugSupportBundleExporter(private val context: Context) {
    fun share(
        results: List<DebugProbeResult>,
        lastAction: DebugActionResult?,
        history: List<DebugHistorySnapshot> = emptyList(),
    ): DebugActionResult {
        if (results.isEmpty()) {
            return DebugActionResult(
                status = DebugProbeStatus.WARN,
                message = "Run probes before exporting a support bundle.",
            )
        }
        return runCatching {
            val directory = File(context.cacheDir, DIRECTORY).apply { mkdirs() }
            pruneOldBundles(directory)
            val file = File(directory, "mmrl-debug-workbench-${System.currentTimeMillis()}.zip")
            writeBundle(file, results, lastAction, history)
            val uri = FileProvider.getUriForFile(context, "${context.packageName}.provider", file)
            val sendIntent = Intent(Intent.ACTION_SEND)
                .setType("application/zip")
                .putExtra(Intent.EXTRA_STREAM, uri)
                .putExtra(Intent.EXTRA_SUBJECT, "MMRL Debug Workbench support bundle")
                .addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            context.startActivity(Intent.createChooser(sendIntent, "Share debug bundle").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
            DebugActionResult(
                status = DebugProbeStatus.PASS,
                message = "Created a sanitized support bundle with redacted probe output.",
            )
        }.getOrElse { error ->
            DebugActionResult(
                status = DebugProbeStatus.FAIL,
                message = error.message ?: "Unable to export Debug Workbench support bundle.",
            )
        }
    }

    private fun writeBundle(
        file: File,
        results: List<DebugProbeResult>,
        lastAction: DebugActionResult?,
        history: List<DebugHistorySnapshot>,
    ) {
        ZipOutputStream(file.outputStream().buffered()).use { zip ->
            zip.writeEntry("debug-report.txt", DebugReportFormatter.asText(results))
            zip.writeEntry("debug-report.json", asJson(results, lastAction, history))
            zip.writeEntry("debug-history.txt", DebugHistoryFormatter.historyText(history))
            zip.writeEntry("debug-history.json", DebugHistoryFormatter.historyJson(history))
            zip.writeEntry(
                "README.txt",
                buildString {
                    appendLine("MMRL Debug Workbench support bundle")
                    appendLine("redacted=true")
                    appendLine("Generated by MMRL package ${context.packageName}")
                    appendLine("This bundle intentionally preserves root module paths, package names, HTTP status codes, probe summaries, and redacted history status changes.")
                    appendLine("GitHub tokens, Authorization headers, and cookies are redacted before export.")
                    appendLine("Debug history is local, bounded, redacted, and contains statuses/summaries only.")
                },
            )
        }
    }

    private fun asJson(
        results: List<DebugProbeResult>,
        lastAction: DebugActionResult?,
        history: List<DebugHistorySnapshot>,
    ): String = buildString {
        val groupedResults = results.groupBy { it.group }.entries.toList()
        appendLine("{")
        appendLine("  \"redacted\": true,")
        appendLine("  \"packageName\": ${context.packageName.json()},")
        appendLine("  \"groups\": [")
        groupedResults.forEachIndexed { groupIndex, (group, groupResults) ->
            appendLine("    {")
            appendLine("      \"id\": ${group.name.json()},")
            appendLine("      \"name\": ${group.displayName.json()},")
            appendLine("      \"results\": [")
            groupResults.forEachIndexed { resultIndex, result ->
                appendLine("        {")
                appendLine("          \"id\": ${result.id.json()},")
                appendLine("          \"title\": ${result.title.json()},")
                appendLine("          \"status\": ${result.status.name.json()},")
                appendLine("          \"summary\": ${DebugRedactor.redact(result.summary).json()},")
                appendLine("          \"evidence\": [")
                result.evidence.forEachIndexed { evidenceIndex, evidence ->
                    appendLine("            {\"label\": ${evidence.label.json()}, \"value\": ${DebugRedactor.redact(evidence.value).json()}}${if (evidenceIndex == result.evidence.lastIndex) "" else ","}")
                }
                appendLine("          ],")
                appendLine("          \"remedies\": [")
                result.remedies.forEachIndexed { remedyIndex, remedy ->
                    appendLine("            ${DebugRedactor.redact(remedy).json()}${if (remedyIndex == result.remedies.lastIndex) "" else ","}")
                }
                appendLine("          ]")
                appendLine("        }${if (resultIndex == groupResults.lastIndex) "" else ","}")
            }
            appendLine("      ]")
            appendLine("    }${if (groupIndex == groupedResults.lastIndex) "" else ","}")
        }
        val lastActionJson = lastAction?.let { action ->
            "{\"status\": ${action.status.name.json()}, \"message\": ${DebugRedactor.redact(action.message).json()}}"
        } ?: "null"
        appendLine("  ],")
        appendLine("  \"lastAction\": $lastActionJson,")
        appendLine("  \"historyCount\": ${history.size}")
        appendLine("}")
    }

    private fun pruneOldBundles(directory: File) {
        val expiry = System.currentTimeMillis() - RETENTION_MS
        directory.listFiles()
            ?.filter { it.isFile && it.lastModified() < expiry }
            ?.forEach { it.delete() }
    }

    private fun ZipOutputStream.writeEntry(name: String, content: String) {
        putNextEntry(ZipEntry(name))
        write(DebugRedactor.redact(content).toByteArray(Charsets.UTF_8))
        closeEntry()
    }

    private fun String.json(): String = buildString {
        append('"')
        this@json.forEach { char ->
            when (char) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> if (char.code < 32) {
                    append("\\u")
                    append(char.code.toString(16).padStart(4, '0').uppercase(Locale.US))
                } else {
                    append(char)
                }
            }
        }
        append('"')
    }

    private companion object {
        const val DIRECTORY = "debug-workbench"
        const val RETENTION_MS = 24L * 60L * 60L * 1000L
    }
}
